version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - lojaly-pontos-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lojaly-pontos
    networks:
      rede:
        ipv4_address: 10.5.0.5
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 13306:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - ./php-make/upload.ini:/usr/local/etc/php/php.ini

volumes:
  lojaly-pontos-data:
networks:
  rede:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1






  